apiVersion: v1
appVersion: V1.0
description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.&#039;'
name: ec
version: 0.1.0
home: ec.zuid-drecht.nl
icon: ec.zuid-drecht.nl
dependencies:
    - name: postgresql
      version: 8.6.4
      repository: https://kubernetes-charts.storage.googleapis.com/
      condition: postgresql.enabled