apiVersion: v1
entries:
  ec:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-02-18T20:22:13.9592075Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 022df0f20e5199969372b2fd9467437cc3b3331141b57c9be1b73cf290426da7
    home: ec.zuid-drecht.nl
    icon: ec.zuid-drecht.nl
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: ec
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - ec-0.1.0.tgz
    version: 0.1.0
  export-component:
  - apiVersion: v1
    appVersion: V1.0
    created: "2021-02-18T20:22:13.9773033Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 4f34eca0b661f2609ef351cc561bef0f5d22b8ab6a574c46a23ea13033903041
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: export-component
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - export-component-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-02-18T20:22:13.9885023Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
generated: "2021-02-18T20:22:13.9347351Z"
